name       : powertop
version    : '2.11'
release    : 8
source     :
    - https://github.com/fenrus75/powertop/archive/v2.11.tar.gz : 770d848005ce0b134bb603f3a3ab2e65acc3236675827d47108b13a75e42b66b
homepage   : https://01.org/powertop
license    : GPL-2.0-or-later
component  : system.utils
summary    : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description: |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
rundeps    :
    - xset
setup      : |
    sed -i "s/RUN-VERSION-SCRIPT-IN-GIT-REPOSITORY-ONLY/$version/" scripts/version
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/powertop.service $installdir/%libdir%/systemd/system/powertop.service
