name       : powertop
version    : '2.10'
release    : 7
source     :
    - https://github.com/fenrus75/powertop/archive/v2.10.tar.gz : 2ca3028b32bcbde0f603e4bf376d546c54730eed1b082e0cd3f3c24462f57a75
homepage   : https://01.org/powertop
license    : GPL-2.0-or-later
component  : system.utils
summary    : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description: |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
rundeps    :
    - xset
setup      : |
    sed -i "s/RUN-VERSION-SCRIPT-IN-GIT-REPOSITORY-ONLY/$version/" scripts/version
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/powertop.service $installdir/%libdir%/systemd/system/powertop.service
