name       : powertop
version    : '2.14'
release    : 11
source     :
    - https://github.com/fenrus75/powertop/archive/refs/tags/v2.14.tar.gz : 0e4cd0933a4f1fe04bfbf9d56efaabc841d9b04d391426f1a3469d6635a25f37
homepage   : https://01.org/powertop
license    : GPL-2.0-only
component  : system.utils
summary    : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description: |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
    - autoconf-archive
rundeps    :
    - xset
setup      : |
    # This fixes aclocal "too many loops" bug reported in https://bugzilla.redhat.com/show_bug.cgi?id=1826935
    autoreconf -fi || autoreconf -fi

    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/powertop.service $installdir/%libdir%/systemd/system/powertop.service
