name       : powertop
version    : '2.9'
release    : 6
source     :
    - https://github.com/fenrus75/powertop/archive/v2.9.tar.gz : 5daf009271a028c55f0d5da7e5cf85ce08f832831957828f0379faf721f5bad1
homepage   : https://01.org/powertop
license    : GPL-2.0-or-later
component  : system.utils
summary    : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description: |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
rundeps    :
    - xset
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
