name       : powertop
version    : '2.12'
release    : 9
source     :
    - https://github.com/fenrus75/powertop/archive/v2.12.tar.gz : 35fbdbf2a02bf6f3558c013d83f4a0e96c2af9a29d0f764b843339f7c39bd1fb
homepage   : https://01.org/powertop
license    : GPL-2.0-only
component  : system.utils
summary    : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description: |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
    - autoconf-archive
rundeps    :
    - xset
setup      : |
    # This fixes aclocal "too many loops" bug reported in https://bugzilla.redhat.com/show_bug.cgi?id=1826935
    autoreconf -fi || autoreconf -fi
    
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/powertop.service $installdir/%libdir%/systemd/system/powertop.service
