name        : powertop
version     : 2.8
release     : 4
source      :
    - https://01.org/sites/default/files/downloads/powertop/powertop-2.8.tar.gz : a87b563f73106babfa3e74dcf92f252938c061e309ace20a361358bbfa579c5a
homepage    : https://01.org/powertop
license     : GPL-2.0
component   : system.utils
summary     : PowerTOP is a Linux tool to diagnose issues with power consumption and power management.
description : |
    PowerTOP is a Linux tool to diagnose issues with power consumption and power management. In addition to being a diagnostic tool, PowerTOP also has an interactive mode where the user can experiment various power management settings for cases where the Linux distribution has not enabled these settings.
builddeps   :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpci)
rundeps     :
    - xset
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
